// This file is auto-generated by @hey-api/openapi-ts

export const DeletedPostSchema = {
  type: 'object',
  properties: {
    id: {
      title: 'ULID',
      type: 'string',
      description: 'Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)',
      format: 'ULID',
      externalDocs: {
        description: 'ULID Specification',
        url: 'https://github.com/ulid/spec',
      },
    },
  },
  additionalProperties: false,
} as const;

export const LikeInfoSchema = {
  type: 'object',
  properties: {
    postId: {
      title: 'ULID',
      type: 'string',
      description: 'Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)',
      format: 'ULID',
      externalDocs: {
        description: 'ULID Specification',
        url: 'https://github.com/ulid/spec',
      },
    },
    userId: {
      type: 'string',
      description: 'The userid of the user that liked the post.',
      nullable: true,
      example: '179944860378202369',
    },
  },
  additionalProperties: false,
} as const;

export const PostSchema = {
  type: 'object',
  properties: {
    id: {
      title: 'ULID',
      type: 'string',
      description: 'ID of the post, defined in the ULID format.',
      format: 'ulid',
      readOnly: true,
      externalDocs: {
        description: 'ULID Specification',
        url: 'https://github.com/ulid/spec',
      },
      example: '01GDMMR85BEHP8AKV8ZGGM259K',
    },
    creator: {
      $ref: '#/components/schemas/PublicUser',
    },
    text: {
      type: 'string',
      description: 'Text for the post. Can be null if the post is only a media post.\nCan contain hashtags and mentions.',
      nullable: true,
      example: 'Hello World! #newpost.',
    },
    mediaUrl: {
      type: 'string',
      description: 'URL - if any - to the media object attached to this post.',
      nullable: true,
      example: 'https://storage.googleapis.com/cas-fee-adv-mumble-api/1094b5e0-5f30-4f0b-a342-ae12936c42ff',
    },
    mediaType: {
      type: 'string',
      description: 'If mediaUrl is set, this field contains the mime type of the media object.',
      nullable: true,
      example: 'image/png',
    },
    likes: {
      type: 'integer',
      description: 'Number of total likes on this post.',
      format: 'int32',
      readOnly: true,
      example: 42,
    },
    likedBySelf: {
      type: 'boolean',
      description:
        'Indicates if the current user liked this post. If the call was made unauthorized,\nthis field is "null" or absent. Otherwise `true` indicates that the authorized user\nliked this post.',
      nullable: true,
      readOnly: true,
    },
    replies: {
      type: 'integer',
      description: 'Number of total replies for this post.',
      format: 'int32',
      readOnly: true,
      example: 42,
    },
  },
  additionalProperties: false,
  description: 'Post in Mumble. This is user generated content.\nPosts can be deleted by the user who created them.',
} as const;

export const PostBaseSchema = {
  type: 'object',
  properties: {
    id: {
      title: 'ULID',
      type: 'string',
      description: 'ID of the post, defined in the ULID format.',
      format: 'ulid',
      readOnly: true,
      externalDocs: {
        description: 'ULID Specification',
        url: 'https://github.com/ulid/spec',
      },
      example: '01GDMMR85BEHP8AKV8ZGGM259K',
    },
    creator: {
      $ref: '#/components/schemas/PublicUser',
    },
    text: {
      type: 'string',
      description: 'Text for the post. Can be null if the post is only a media post.\nCan contain hashtags and mentions.',
      nullable: true,
      example: 'Hello World! #newpost.',
    },
    mediaUrl: {
      type: 'string',
      description: 'URL - if any - to the media object attached to this post.',
      nullable: true,
      example: 'https://storage.googleapis.com/cas-fee-adv-mumble-api/1094b5e0-5f30-4f0b-a342-ae12936c42ff',
    },
    mediaType: {
      type: 'string',
      description: 'If mediaUrl is set, this field contains the mime type of the media object.',
      nullable: true,
      example: 'image/png',
    },
    likes: {
      type: 'integer',
      description: 'Number of total likes on this post.',
      format: 'int32',
      readOnly: true,
      example: 42,
    },
    likedBySelf: {
      type: 'boolean',
      description:
        'Indicates if the current user liked this post. If the call was made unauthorized,\nthis field is "null" or absent. Otherwise `true` indicates that the authorized user\nliked this post.',
      nullable: true,
      readOnly: true,
    },
  },
  additionalProperties: false,
} as const;

export const PostPaginatedResultSchema = {
  type: 'object',
  properties: {
    count: {
      type: 'integer',
      description: 'The total count of results.',
      format: 'int32',
      readOnly: true,
      example: 1337,
    },
    data: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/Post',
      },
      description: 'The data for this given page.',
      readOnly: true,
    },
    next: {
      type: 'string',
      description:
        'Link to next page. If this is null, there is no next page.\nThe link will contain pagination information (offset, limit).\nIf returned by a search, the link will not contain the search parameters.',
      nullable: true,
      readOnly: true,
    },
    previous: {
      type: 'string',
      description:
        'Link to previous page. If this is null, there is no next page.\nThe link will contain pagination information (offset, limit).\nIf returned by a search, the link will not contain the search parameters.',
      nullable: true,
      readOnly: true,
    },
  },
  additionalProperties: false,
  description: 'Paginated API result that contains arbitrary\ndata and an optional link for the next / previous page.',
} as const;

export const PublicUserSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      description: 'ID of the user who created the post.',
      nullable: true,
      readOnly: true,
      example: '179944860378202369',
    },
    username: {
      type: 'string',
      description: 'The username of the creator.',
      nullable: true,
      example: 'max_muster',
    },
    avatarUrl: {
      type: 'string',
      description: 'If set, points to the avatar of the user.',
      nullable: true,
      readOnly: true,
    },
  },
  additionalProperties: false,
  description:
    'Public user information. This information is publicly available to everyone.\nIt contains basic information such as the ID.',
} as const;

export const ReplySchema = {
  type: 'object',
  properties: {
    id: {
      title: 'ULID',
      type: 'string',
      description: 'ID of the post, defined in the ULID format.',
      format: 'ulid',
      readOnly: true,
      externalDocs: {
        description: 'ULID Specification',
        url: 'https://github.com/ulid/spec',
      },
      example: '01GDMMR85BEHP8AKV8ZGGM259K',
    },
    creator: {
      $ref: '#/components/schemas/PublicUser',
    },
    text: {
      type: 'string',
      description: 'Text for the post. Can be null if the post is only a media post.\nCan contain hashtags and mentions.',
      nullable: true,
      example: 'Hello World! #newpost.',
    },
    mediaUrl: {
      type: 'string',
      description: 'URL - if any - to the media object attached to this post.',
      nullable: true,
      example: 'https://storage.googleapis.com/cas-fee-adv-mumble-api/1094b5e0-5f30-4f0b-a342-ae12936c42ff',
    },
    mediaType: {
      type: 'string',
      description: 'If mediaUrl is set, this field contains the mime type of the media object.',
      nullable: true,
      example: 'image/png',
    },
    likes: {
      type: 'integer',
      description: 'Number of total likes on this post.',
      format: 'int32',
      readOnly: true,
      example: 42,
    },
    likedBySelf: {
      type: 'boolean',
      description:
        'Indicates if the current user liked this post. If the call was made unauthorized,\nthis field is "null" or absent. Otherwise `true` indicates that the authorized user\nliked this post.',
      nullable: true,
      readOnly: true,
    },
    parentId: {
      title: 'ULID',
      type: 'string',
      description: 'The ID of the parent post.',
      format: 'ULID',
      readOnly: true,
      externalDocs: {
        description: 'ULID Specification',
        url: 'https://github.com/ulid/spec',
      },
    },
  },
  additionalProperties: false,
  description: 'A reply to a post.',
} as const;

export const ReplyPaginatedResultSchema = {
  type: 'object',
  properties: {
    count: {
      type: 'integer',
      description: 'The total count of results.',
      format: 'int32',
      readOnly: true,
      example: 1337,
    },
    data: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/Reply',
      },
      description: 'The data for this given page.',
      readOnly: true,
    },
    next: {
      type: 'string',
      description:
        'Link to next page. If this is null, there is no next page.\nThe link will contain pagination information (offset, limit).\nIf returned by a search, the link will not contain the search parameters.',
      nullable: true,
      readOnly: true,
    },
    previous: {
      type: 'string',
      description:
        'Link to previous page. If this is null, there is no next page.\nThe link will contain pagination information (offset, limit).\nIf returned by a search, the link will not contain the search parameters.',
      nullable: true,
      readOnly: true,
    },
  },
  additionalProperties: false,
  description: 'Paginated API result that contains arbitrary\ndata and an optional link for the next / previous page.',
} as const;

export const UpdatePostDataSchema = {
  type: 'object',
  properties: {
    text: {
      type: 'string',
      description:
        'Text for the post. If omitted, the text will not be updated.\nIf set to empty string, the text will be removed.',
      nullable: true,
      writeOnly: true,
    },
  },
  additionalProperties: false,
  description: 'Data that is used to patch a given post.',
} as const;

export const UpdateUserDataSchema = {
  type: 'object',
  properties: {
    firstname: {
      type: 'string',
      description: 'If set, updates the firstname of the profile.',
      nullable: true,
      writeOnly: true,
    },
    lastname: {
      type: 'string',
      description: 'If set, updates the lastname of the profile.',
      nullable: true,
      writeOnly: true,
    },
    username: {
      type: 'string',
      description: 'If set, updates the username of the profile.',
      nullable: true,
      writeOnly: true,
    },
  },
  additionalProperties: false,
  description: 'Model to update user data.',
} as const;

export const UserSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      description: 'ID of the user who created the post.',
      nullable: true,
      readOnly: true,
      example: '179944860378202369',
    },
    username: {
      type: 'string',
      description: 'The username of the creator.',
      nullable: true,
      example: 'max_muster',
    },
    avatarUrl: {
      type: 'string',
      description: 'If set, points to the avatar of the user.',
      nullable: true,
      readOnly: true,
    },
    firstname: {
      type: 'string',
      description: 'Firstname of the user.',
      nullable: true,
    },
    lastname: {
      type: 'string',
      description: 'Lastname of the user.',
      nullable: true,
    },
  },
  additionalProperties: false,
  description:
    'User information inside Mumble. This information can only be fetched\nwhen requested by an authenticated user.',
} as const;

export const UserPaginatedResultSchema = {
  type: 'object',
  properties: {
    count: {
      type: 'integer',
      description: 'The total count of results.',
      format: 'int32',
      readOnly: true,
      example: 1337,
    },
    data: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/User',
      },
      description: 'The data for this given page.',
      readOnly: true,
    },
    next: {
      type: 'string',
      description:
        'Link to next page. If this is null, there is no next page.\nThe link will contain pagination information (offset, limit).\nIf returned by a search, the link will not contain the search parameters.',
      nullable: true,
      readOnly: true,
    },
    previous: {
      type: 'string',
      description:
        'Link to previous page. If this is null, there is no next page.\nThe link will contain pagination information (offset, limit).\nIf returned by a search, the link will not contain the search parameters.',
      nullable: true,
      readOnly: true,
    },
  },
  additionalProperties: false,
  description: 'Paginated API result that contains arbitrary\ndata and an optional link for the next / previous page.',
} as const;

export const PostWritableSchema = {
  type: 'object',
  properties: {
    creator: {
      $ref: '#/components/schemas/PublicUserWritable',
    },
    text: {
      type: 'string',
      description: 'Text for the post. Can be null if the post is only a media post.\nCan contain hashtags and mentions.',
      nullable: true,
      example: 'Hello World! #newpost.',
    },
    mediaUrl: {
      type: 'string',
      description: 'URL - if any - to the media object attached to this post.',
      nullable: true,
      example: 'https://storage.googleapis.com/cas-fee-adv-mumble-api/1094b5e0-5f30-4f0b-a342-ae12936c42ff',
    },
    mediaType: {
      type: 'string',
      description: 'If mediaUrl is set, this field contains the mime type of the media object.',
      nullable: true,
      example: 'image/png',
    },
  },
  additionalProperties: false,
  description: 'Post in Mumble. This is user generated content.\nPosts can be deleted by the user who created them.',
} as const;

export const PostBaseWritableSchema = {
  type: 'object',
  properties: {
    creator: {
      $ref: '#/components/schemas/PublicUserWritable',
    },
    text: {
      type: 'string',
      description: 'Text for the post. Can be null if the post is only a media post.\nCan contain hashtags and mentions.',
      nullable: true,
      example: 'Hello World! #newpost.',
    },
    mediaUrl: {
      type: 'string',
      description: 'URL - if any - to the media object attached to this post.',
      nullable: true,
      example: 'https://storage.googleapis.com/cas-fee-adv-mumble-api/1094b5e0-5f30-4f0b-a342-ae12936c42ff',
    },
    mediaType: {
      type: 'string',
      description: 'If mediaUrl is set, this field contains the mime type of the media object.',
      nullable: true,
      example: 'image/png',
    },
  },
  additionalProperties: false,
} as const;

export const PostPaginatedResultWritableSchema = {
  type: 'object',
  additionalProperties: false,
  description: 'Paginated API result that contains arbitrary\ndata and an optional link for the next / previous page.',
} as const;

export const PublicUserWritableSchema = {
  type: 'object',
  properties: {
    username: {
      type: 'string',
      description: 'The username of the creator.',
      nullable: true,
      example: 'max_muster',
    },
  },
  additionalProperties: false,
  description:
    'Public user information. This information is publicly available to everyone.\nIt contains basic information such as the ID.',
} as const;

export const ReplyWritableSchema = {
  type: 'object',
  properties: {
    creator: {
      $ref: '#/components/schemas/PublicUserWritable',
    },
    text: {
      type: 'string',
      description: 'Text for the post. Can be null if the post is only a media post.\nCan contain hashtags and mentions.',
      nullable: true,
      example: 'Hello World! #newpost.',
    },
    mediaUrl: {
      type: 'string',
      description: 'URL - if any - to the media object attached to this post.',
      nullable: true,
      example: 'https://storage.googleapis.com/cas-fee-adv-mumble-api/1094b5e0-5f30-4f0b-a342-ae12936c42ff',
    },
    mediaType: {
      type: 'string',
      description: 'If mediaUrl is set, this field contains the mime type of the media object.',
      nullable: true,
      example: 'image/png',
    },
  },
  additionalProperties: false,
  description: 'A reply to a post.',
} as const;

export const ReplyPaginatedResultWritableSchema = {
  type: 'object',
  additionalProperties: false,
  description: 'Paginated API result that contains arbitrary\ndata and an optional link for the next / previous page.',
} as const;

export const UserWritableSchema = {
  type: 'object',
  properties: {
    username: {
      type: 'string',
      description: 'The username of the creator.',
      nullable: true,
      example: 'max_muster',
    },
    firstname: {
      type: 'string',
      description: 'Firstname of the user.',
      nullable: true,
    },
    lastname: {
      type: 'string',
      description: 'Lastname of the user.',
      nullable: true,
    },
  },
  additionalProperties: false,
  description:
    'User information inside Mumble. This information can only be fetched\nwhen requested by an authenticated user.',
} as const;

export const UserPaginatedResultWritableSchema = {
  type: 'object',
  additionalProperties: false,
  description: 'Paginated API result that contains arbitrary\ndata and an optional link for the next / previous page.',
} as const;
