// This file is auto-generated by @hey-api/openapi-ts
import { type Client, type Options as Options2, type TDataShape, formDataBodySerializer } from './client';
import { client } from './client.gen';
import type {
  DeletePostsByIdData,
  DeletePostsByIdErrors,
  DeletePostsByIdLikesData,
  DeletePostsByIdLikesErrors,
  DeletePostsByIdLikesResponses,
  DeletePostsByIdMediaData,
  DeletePostsByIdMediaErrors,
  DeletePostsByIdMediaResponses,
  DeletePostsByIdResponses,
  DeleteUsersAvatarData,
  DeleteUsersAvatarErrors,
  DeleteUsersAvatarResponses,
  DeleteUsersByIdFollowersData,
  DeleteUsersByIdFollowersErrors,
  DeleteUsersByIdFollowersResponses,
  GetPostsByIdData,
  GetPostsByIdErrors,
  GetPostsByIdRepliesData,
  GetPostsByIdRepliesErrors,
  GetPostsByIdRepliesResponses,
  GetPostsByIdResponses,
  GetPostsData,
  GetPostsErrors,
  GetPostsResponses,
  GetPostsSseData,
  GetPostsSseErrors,
  GetPostsSseResponses,
  GetUsersByIdData,
  GetUsersByIdErrors,
  GetUsersByIdFolloweesData,
  GetUsersByIdFolloweesErrors,
  GetUsersByIdFolloweesResponses,
  GetUsersByIdFollowersData,
  GetUsersByIdFollowersErrors,
  GetUsersByIdFollowersResponses,
  GetUsersByIdResponses,
  GetUsersData,
  GetUsersErrors,
  GetUsersResponses,
  PatchPostsByIdData,
  PatchPostsByIdErrors,
  PatchPostsByIdResponses,
  PatchUsersData,
  PatchUsersErrors,
  PatchUsersResponses,
  PostPostsByIdRepliesData,
  PostPostsByIdRepliesErrors,
  PostPostsByIdRepliesResponses,
  PostPostsData,
  PostPostsErrors,
  PostPostsResponses,
  PutPostsByIdData,
  PutPostsByIdErrors,
  PutPostsByIdLikesData,
  PutPostsByIdLikesErrors,
  PutPostsByIdLikesResponses,
  PutPostsByIdMediaData,
  PutPostsByIdMediaErrors,
  PutPostsByIdMediaResponses,
  PutPostsByIdResponses,
  PutUsersAvatarData,
  PutUsersAvatarErrors,
  PutUsersAvatarResponses,
  PutUsersByIdFollowersData,
  PutUsersByIdFollowersErrors,
  PutUsersByIdFollowersResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Fetch/Search a paginated list of posts.
 *
 * Fetch or search a paginated list of posts, ordered by the time of their creation.
 */
export const getPosts = <ThrowOnError extends boolean = false>(options?: Options<GetPostsData, ThrowOnError>) =>
  (options?.client ?? client).get<GetPostsResponses, GetPostsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts',
    ...options,
  });

/**
 * Create a new post.
 *
 * Create a new post with the logged in user. A post can contain text and/or an image. Either text or the image must be provided, otherwise a BadRequest is returned. Upload Limit: 2 MB.
 */
export const postPosts = <ThrowOnError extends boolean = false>(options?: Options<PostPostsData, ThrowOnError>) =>
  (options?.client ?? client).post<PostPostsResponses, PostPostsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });

/**
 * Delete a given post.
 *
 * This can be a post or a reply. The post is marked as deleted and will not be returned in any search.
 */
export const deletePostsById = <ThrowOnError extends boolean = false>(options: Options<DeletePostsByIdData, ThrowOnError>) =>
  (options.client ?? client).delete<DeletePostsByIdResponses, DeletePostsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}',
    ...options,
  });

/**
 * Fetch a specific post with the given ID.
 */
export const getPostsById = <ThrowOnError extends boolean = false>(options: Options<GetPostsByIdData, ThrowOnError>) =>
  (options.client ?? client).get<GetPostsByIdResponses, GetPostsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}',
    ...options,
  });

/**
 * Partial update of a post.
 *
 * This partially updates (patches) a post with the given ID. All fields that are "null" are ignored and not updated. If the post text is set to an empty string, it will be removed (null). The post must always have either text or media. If this patch results in a post with no text and no media, a BadRequest is returned.
 */
export const patchPostsById = <ThrowOnError extends boolean = false>(options: Options<PatchPostsByIdData, ThrowOnError>) =>
  (options.client ?? client).patch<PatchPostsByIdResponses, PatchPostsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update a post with the given ID.
 *
 * Update (replace) a post. This replaces the entire post. If the post does not exist, a NotFound is returned. If the post is not valid (has no text and no media), a BadRequest is returned. There is no partial update on this method.
 */
export const putPostsById = <ThrowOnError extends boolean = false>(options: Options<PutPostsByIdData, ThrowOnError>) =>
  (options.client ?? client).put<PutPostsByIdResponses, PutPostsByIdErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Remove the media of a post.
 *
 * Remove the media of a post with the given ID. The post must always have either text or media. If this delete results in a post with no text and no media, a BadRequest is returned.
 */
export const deletePostsByIdMedia = <ThrowOnError extends boolean = false>(
  options: Options<DeletePostsByIdMediaData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeletePostsByIdMediaResponses, DeletePostsByIdMediaErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/media',
    ...options,
  });

/**
 * Update the media of a post.
 *
 * This replaces the entire media of the post and returns the new media URL.
 */
export const putPostsByIdMedia = <ThrowOnError extends boolean = false>(
  options: Options<PutPostsByIdMediaData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutPostsByIdMediaResponses, PutPostsByIdMediaErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/media',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Fetch a list of replies.
 *
 * Fetch a list of (paginated) replies for a given post. There is only one level for replies. Replies cannot have replies. Trying to fetch replies for a reply will result in a BadRequest.
 */
export const getPostsByIdReplies = <ThrowOnError extends boolean = false>(
  options: Options<GetPostsByIdRepliesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPostsByIdRepliesResponses, GetPostsByIdRepliesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/replies',
    ...options,
  });

/**
 * Create a reply to a post.
 *
 * Create a new reply to a post. It is not possible to create a reply to a reply. This results in a BadRequest.
 */
export const postPostsByIdReplies = <ThrowOnError extends boolean = false>(
  options: Options<PostPostsByIdRepliesData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPostsByIdRepliesResponses, PostPostsByIdRepliesErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/replies',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Unlike a post.
 *
 * Unlike the given post for the current user. If the user does not like the post, nothing is updated.
 */
export const deletePostsByIdLikes = <ThrowOnError extends boolean = false>(
  options: Options<DeletePostsByIdLikesData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeletePostsByIdLikesResponses, DeletePostsByIdLikesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/likes',
    ...options,
  });

/**
 * Like a post.
 *
 *  A user can only like a post once. This is an idempotent operation. If the user already likes the post, nothing is updated.
 */
export const putPostsByIdLikes = <ThrowOnError extends boolean = false>(
  options: Options<PutPostsByIdLikesData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutPostsByIdLikesResponses, PutPostsByIdLikesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/likes',
    ...options,
  });

/**
 * Fetch a paginated list of users.
 *
 * Fetch a paginated list of users. If the caller is authenticated, the user list will contain more data.
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) =>
  (options?.client ?? client).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options,
  });

/**
 * Update the authenticated user profile.
 *
 * Update the current authenticated user profile. Returns a bad request if fields are set to an empty string. Omitting a field does not update them. Uploading an avatar is done via the /users/avatar endpoint. The username is unique, duplicating it results in an error.
 */
export const patchUsers = <ThrowOnError extends boolean = false>(options?: Options<PatchUsersData, ThrowOnError>) =>
  (options?.client ?? client).patch<PatchUsersResponses, PatchUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Get a specific user by their ID.
 *
 * Fetch a specific user profile from the API. If the caller is authenticated, more information than the public profile is provided.
 */
export const getUsersById = <ThrowOnError extends boolean = false>(options: Options<GetUsersByIdData, ThrowOnError>) =>
  (options.client ?? client).get<GetUsersByIdResponses, GetUsersByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options,
  });

/**
 * Remove an avatar.
 *
 * Remove the current avatar picture (if any) for the actual authenticated user.
 */
export const deleteUsersAvatar = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteUsersAvatarData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<DeleteUsersAvatarResponses, DeleteUsersAvatarErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/avatar',
    ...options,
  });

/**
 * Upload an avatar.
 *
 * Upload an avatar picture for the actual authenticated user. Returns the new media url to the uploaded user avatar. Upload limit: 0.5 MB.
 */
export const putUsersAvatar = <ThrowOnError extends boolean = false>(options?: Options<PutUsersAvatarData, ThrowOnError>) =>
  (options?.client ?? client).put<PutUsersAvatarResponses, PutUsersAvatarErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/avatar',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });

/**
 * Unfollow a user.
 *
 * Remove the currently authenticated user from the follower list of the given user (id). User A (authenticated) calls this endpoint to unfollow user B (id).
 */
export const deleteUsersByIdFollowers = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUsersByIdFollowersData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteUsersByIdFollowersResponses, DeleteUsersByIdFollowersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}/followers',
    ...options,
  });

/**
 * Fetch a list of followers.
 *
 *  Fetch a (paginated) list of followers for a given user (All users that follow the given user). Returns only public information (public profile).
 */
export const getUsersByIdFollowers = <ThrowOnError extends boolean = false>(
  options: Options<GetUsersByIdFollowersData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetUsersByIdFollowersResponses, GetUsersByIdFollowersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}/followers',
    ...options,
  });

/**
 * Follow a user.
 *
 * Add the currently authenticated user as a follower to the given user (id). User A (authenticated) calls this endpoint to follow user B (id).
 */
export const putUsersByIdFollowers = <ThrowOnError extends boolean = false>(
  options: Options<PutUsersByIdFollowersData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutUsersByIdFollowersResponses, PutUsersByIdFollowersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}/followers',
    ...options,
  });

/**
 * Fetch a list of followees.
 *
 * Fetch a (paginated) list of followees for a given user(All users that are being followed by the given user). Returns only public information (public profile).
 */
export const getUsersByIdFollowees = <ThrowOnError extends boolean = false>(
  options: Options<GetUsersByIdFolloweesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetUsersByIdFolloweesResponses, GetUsersByIdFolloweesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}/followees',
    ...options,
  });

/**
 * Get a stream of new or updated posts via Server Sent Event push.
 *
 * The server sent events contain newly created posts as well as updated posts.
 * Depending on the authentication state, the post contain more or less information.
 *
 * Currently, the following events are supported:
 * - postCreated (for creating a new post or a reply)
 * - postUpdated
 * - postDeleted
 * - postLiked
 * - postUnliked
 *
 * As an example, using the posts server sent events in javascript is done as follows:
 * ```js
 * const evtSource = new EventSource("/posts/_sse");
 * evtSource.addEventListener('postCreated', (e) => console.log(e.data));
 * ```
 *
 * You may read more about server sent events in the
 * [documentation about Using Server Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events)
 */
export const getPostsSse = <ThrowOnError extends boolean = false>(options?: Options<GetPostsSseData, ThrowOnError>) =>
  (options?.client ?? client).sse.get<GetPostsSseResponses, GetPostsSseErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/_sse',
    ...options,
  });
