// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://mumble-api-prod-714602723919.europe-west6.run.app' | (string & {});
};

export type DeletedPost = {
  /**
   * ULID
   *
   * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
   */
  id?: string;
};

export type LikeInfo = {
  /**
   * ULID
   *
   * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
   */
  postId?: string;
  /**
   * The userid of the user that liked the post.
   */
  userId?: string | null;
};

/**
 * Post in Mumble. This is user generated content.
 * Posts can be deleted by the user who created them.
 */
export type Post = {
  /**
   * ULID
   *
   * ID of the post, defined in the ULID format.
   */
  readonly id?: string;
  creator?: PublicUser;
  /**
   * Text for the post. Can be null if the post is only a media post.
   * Can contain hashtags and mentions.
   */
  text?: string | null;
  /**
   * URL - if any - to the media object attached to this post.
   */
  mediaUrl?: string | null;
  /**
   * If mediaUrl is set, this field contains the mime type of the media object.
   */
  mediaType?: string | null;
  /**
   * Number of total likes on this post.
   */
  readonly likes?: number;
  /**
   * Indicates if the current user liked this post. If the call was made unauthorized,
   * this field is "null" or absent. Otherwise `true` indicates that the authorized user
   * liked this post.
   */
  readonly likedBySelf?: boolean | null;
  /**
   * Number of total replies for this post.
   */
  readonly replies?: number;
};

export type PostBase = {
  /**
   * ULID
   *
   * ID of the post, defined in the ULID format.
   */
  readonly id?: string;
  creator?: PublicUser;
  /**
   * Text for the post. Can be null if the post is only a media post.
   * Can contain hashtags and mentions.
   */
  text?: string | null;
  /**
   * URL - if any - to the media object attached to this post.
   */
  mediaUrl?: string | null;
  /**
   * If mediaUrl is set, this field contains the mime type of the media object.
   */
  mediaType?: string | null;
  /**
   * Number of total likes on this post.
   */
  readonly likes?: number;
  /**
   * Indicates if the current user liked this post. If the call was made unauthorized,
   * this field is "null" or absent. Otherwise `true` indicates that the authorized user
   * liked this post.
   */
  readonly likedBySelf?: boolean | null;
};

/**
 * Paginated API result that contains arbitrary
 * data and an optional link for the next / previous page.
 */
export type PostPaginatedResult = {
  /**
   * The total count of results.
   */
  readonly count?: number;
  /**
   * The data for this given page.
   */
  readonly data?: Array<Post>;
  /**
   * Link to next page. If this is null, there is no next page.
   * The link will contain pagination information (offset, limit).
   * If returned by a search, the link will not contain the search parameters.
   */
  readonly next?: string | null;
  /**
   * Link to previous page. If this is null, there is no next page.
   * The link will contain pagination information (offset, limit).
   * If returned by a search, the link will not contain the search parameters.
   */
  readonly previous?: string | null;
};

/**
 * Public user information. This information is publicly available to everyone.
 * It contains basic information such as the ID.
 */
export type PublicUser = {
  /**
   * ID of the user who created the post.
   */
  readonly id?: string | null;
  /**
   * The username of the creator.
   */
  username?: string | null;
  /**
   * If set, points to the avatar of the user.
   */
  readonly avatarUrl?: string | null;
};

/**
 * A reply to a post.
 */
export type Reply = {
  /**
   * ULID
   *
   * ID of the post, defined in the ULID format.
   */
  readonly id?: string;
  creator?: PublicUser;
  /**
   * Text for the post. Can be null if the post is only a media post.
   * Can contain hashtags and mentions.
   */
  text?: string | null;
  /**
   * URL - if any - to the media object attached to this post.
   */
  mediaUrl?: string | null;
  /**
   * If mediaUrl is set, this field contains the mime type of the media object.
   */
  mediaType?: string | null;
  /**
   * Number of total likes on this post.
   */
  readonly likes?: number;
  /**
   * Indicates if the current user liked this post. If the call was made unauthorized,
   * this field is "null" or absent. Otherwise `true` indicates that the authorized user
   * liked this post.
   */
  readonly likedBySelf?: boolean | null;
  /**
   * ULID
   *
   * The ID of the parent post.
   */
  readonly parentId?: string;
};

/**
 * Paginated API result that contains arbitrary
 * data and an optional link for the next / previous page.
 */
export type ReplyPaginatedResult = {
  /**
   * The total count of results.
   */
  readonly count?: number;
  /**
   * The data for this given page.
   */
  readonly data?: Array<Reply>;
  /**
   * Link to next page. If this is null, there is no next page.
   * The link will contain pagination information (offset, limit).
   * If returned by a search, the link will not contain the search parameters.
   */
  readonly next?: string | null;
  /**
   * Link to previous page. If this is null, there is no next page.
   * The link will contain pagination information (offset, limit).
   * If returned by a search, the link will not contain the search parameters.
   */
  readonly previous?: string | null;
};

/**
 * Data that is used to patch a given post.
 */
export type UpdatePostData = {
  /**
   * Text for the post. If omitted, the text will not be updated.
   * If set to empty string, the text will be removed.
   */
  text?: string | null;
};

/**
 * Model to update user data.
 */
export type UpdateUserData = {
  /**
   * If set, updates the firstname of the profile.
   */
  firstname?: string | null;
  /**
   * If set, updates the lastname of the profile.
   */
  lastname?: string | null;
  /**
   * If set, updates the username of the profile.
   */
  username?: string | null;
};

/**
 * User information inside Mumble. This information can only be fetched
 * when requested by an authenticated user.
 */
export type User = {
  /**
   * ID of the user who created the post.
   */
  readonly id?: string | null;
  /**
   * The username of the creator.
   */
  username?: string | null;
  /**
   * If set, points to the avatar of the user.
   */
  readonly avatarUrl?: string | null;
  /**
   * Firstname of the user.
   */
  firstname?: string | null;
  /**
   * Lastname of the user.
   */
  lastname?: string | null;
};

/**
 * Paginated API result that contains arbitrary
 * data and an optional link for the next / previous page.
 */
export type UserPaginatedResult = {
  /**
   * The total count of results.
   */
  readonly count?: number;
  /**
   * The data for this given page.
   */
  readonly data?: Array<User>;
  /**
   * Link to next page. If this is null, there is no next page.
   * The link will contain pagination information (offset, limit).
   * If returned by a search, the link will not contain the search parameters.
   */
  readonly next?: string | null;
  /**
   * Link to previous page. If this is null, there is no next page.
   * The link will contain pagination information (offset, limit).
   * If returned by a search, the link will not contain the search parameters.
   */
  readonly previous?: string | null;
};

/**
 * Post in Mumble. This is user generated content.
 * Posts can be deleted by the user who created them.
 */
export type PostWritable = {
  creator?: PublicUserWritable;
  /**
   * Text for the post. Can be null if the post is only a media post.
   * Can contain hashtags and mentions.
   */
  text?: string | null;
  /**
   * URL - if any - to the media object attached to this post.
   */
  mediaUrl?: string | null;
  /**
   * If mediaUrl is set, this field contains the mime type of the media object.
   */
  mediaType?: string | null;
};

export type PostBaseWritable = {
  creator?: PublicUserWritable;
  /**
   * Text for the post. Can be null if the post is only a media post.
   * Can contain hashtags and mentions.
   */
  text?: string | null;
  /**
   * URL - if any - to the media object attached to this post.
   */
  mediaUrl?: string | null;
  /**
   * If mediaUrl is set, this field contains the mime type of the media object.
   */
  mediaType?: string | null;
};

/**
 * Paginated API result that contains arbitrary
 * data and an optional link for the next / previous page.
 */
export type PostPaginatedResultWritable = {
  [key: string]: never;
};

/**
 * Public user information. This information is publicly available to everyone.
 * It contains basic information such as the ID.
 */
export type PublicUserWritable = {
  /**
   * The username of the creator.
   */
  username?: string | null;
};

/**
 * A reply to a post.
 */
export type ReplyWritable = {
  creator?: PublicUserWritable;
  /**
   * Text for the post. Can be null if the post is only a media post.
   * Can contain hashtags and mentions.
   */
  text?: string | null;
  /**
   * URL - if any - to the media object attached to this post.
   */
  mediaUrl?: string | null;
  /**
   * If mediaUrl is set, this field contains the mime type of the media object.
   */
  mediaType?: string | null;
};

/**
 * Paginated API result that contains arbitrary
 * data and an optional link for the next / previous page.
 */
export type ReplyPaginatedResultWritable = {
  [key: string]: never;
};

/**
 * User information inside Mumble. This information can only be fetched
 * when requested by an authenticated user.
 */
export type UserWritable = {
  /**
   * The username of the creator.
   */
  username?: string | null;
  /**
   * Firstname of the user.
   */
  firstname?: string | null;
  /**
   * Lastname of the user.
   */
  lastname?: string | null;
};

/**
 * Paginated API result that contains arbitrary
 * data and an optional link for the next / previous page.
 */
export type UserPaginatedResultWritable = {
  [key: string]: never;
};

export type GetPostsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * ULID
     *
     * ID of a post. If set, only return posts that are newer than the given post ID.
     * If omitted, no newer than filter is applied. The ID is a ULID (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G).
     */
    newerThan?: string;
    /**
     * ULID
     *
     * ID of a post. If set, only return posts that are older than the given post ID.
     * If omitted, no older than filter is applied.
     */
    olderThan?: string;
    /**
     * If set, search for posts that contain a specific text.
     */
    text?: string;
    /**
     * Search for posts that contain this tag (#TEXT).
     */
    tags?: Array<string>;
    /**
     * Search for posts that were created by one of the given users (ID).
     * All IDs must be valid user IDs and are "OR"ed.
     */
    creators?: Array<string>;
    /**
     * Search for posts that were liked by specific user(s).
     * Multiple user IDs are "OR"ed (if a post is liked by user A OR B).
     */
    likedBy?: Array<string>;
    /**
     * The offset for pagination of further calls. Defaults to 0 if omitted.
     */
    offset?: number;
    /**
     * The limit of items to return. Minimum is 1, maximum is 1000.
     * Defaults to 100.
     */
    limit?: number;
  };
  url: '/posts';
};

export type GetPostsErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPostsResponses = {
  /**
   * Success
   */
  200: PostPaginatedResult;
};

export type GetPostsResponse = GetPostsResponses[keyof GetPostsResponses];

export type PostPostsData = {
  body?: {
    /**
     * Text for the new post. If not set, a media file must be set.
     * If both are omitted, the API will return a 400 Bad Request.
     */
    text?: string;
    /**
     * Media file for the post. If not set, a text must be set.
     * If both are omitted, the API will return a 400 Bad Request.
     */
    media?: Blob | File;
  };
  path?: never;
  query?: never;
  url: '/posts';
};

export type PostPostsErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostPostsResponses = {
  /**
   * Success - Created a new Post
   */
  200: Post;
};

export type PostPostsResponse = PostPostsResponses[keyof PostPostsResponses];

export type DeletePostsByIdData = {
  body?: never;
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}';
};

export type DeletePostsByIdErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeletePostsByIdResponses = {
  /**
   * Success - No Content
   */
  204: void;
};

export type DeletePostsByIdResponse = DeletePostsByIdResponses[keyof DeletePostsByIdResponses];

export type GetPostsByIdData = {
  body?: never;
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}';
};

export type GetPostsByIdErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPostsByIdResponses = {
  /**
   * Success
   */
  200: Post;
};

export type GetPostsByIdResponse = GetPostsByIdResponses[keyof GetPostsByIdResponses];

export type PatchPostsByIdData = {
  body: UpdatePostData;
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}';
};

export type PatchPostsByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PatchPostsByIdResponses = {
  /**
   * Success - No Content
   */
  204: void;
};

export type PatchPostsByIdResponse = PatchPostsByIdResponses[keyof PatchPostsByIdResponses];

export type PutPostsByIdData = {
  body?: {
    /**
     * Text for the new post. If not set, a media file must be set.
     * If both are omitted, the API will return a 400 Bad Request.
     */
    text?: string;
    /**
     * Media file for the post. If not set, a text must be set.
     * If both are omitted, the API will return a 400 Bad Request.
     */
    media?: Blob | File;
  };
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}';
};

export type PutPostsByIdErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutPostsByIdResponses = {
  /**
   * Success - Replaced the Post
   */
  200: Post;
};

export type PutPostsByIdResponse = PutPostsByIdResponses[keyof PutPostsByIdResponses];

export type DeletePostsByIdMediaData = {
  body?: never;
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}/media';
};

export type DeletePostsByIdMediaErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeletePostsByIdMediaResponses = {
  /**
   * Success - No Content
   */
  204: void;
};

export type DeletePostsByIdMediaResponse = DeletePostsByIdMediaResponses[keyof DeletePostsByIdMediaResponses];

export type PutPostsByIdMediaData = {
  body?: {
    /**
     * Media file for the upload.
     */
    media?: Blob | File;
  };
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}/media';
};

export type PutPostsByIdMediaErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutPostsByIdMediaResponses = {
  /**
   * Success
   */
  200: string;
};

export type PutPostsByIdMediaResponse = PutPostsByIdMediaResponses[keyof PutPostsByIdMediaResponses];

export type GetPostsByIdRepliesData = {
  body?: never;
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: {
    /**
     * The offset for pagination of further calls. Defaults to 0 if omitted.
     */
    offset?: number;
    /**
     * The limit of items to return. Minimum is 1, maximum is 1000.
     * Defaults to 100.
     */
    limit?: number;
  };
  url: '/posts/{id}/replies';
};

export type GetPostsByIdRepliesErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPostsByIdRepliesResponses = {
  /**
   * Success
   */
  200: ReplyPaginatedResult;
};

export type GetPostsByIdRepliesResponse = GetPostsByIdRepliesResponses[keyof GetPostsByIdRepliesResponses];

export type PostPostsByIdRepliesData = {
  body?: {
    /**
     * Text for the new post. If not set, a media file must be set.
     * If both are omitted, the API will return a 400 Bad Request.
     */
    text?: string;
    /**
     * Media file for the post. If not set, a text must be set.
     * If both are omitted, the API will return a 400 Bad Request.
     */
    media?: Blob | File;
  };
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}/replies';
};

export type PostPostsByIdRepliesErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PostPostsByIdRepliesResponses = {
  /**
   * Success
   */
  200: Reply;
};

export type PostPostsByIdRepliesResponse = PostPostsByIdRepliesResponses[keyof PostPostsByIdRepliesResponses];

export type DeletePostsByIdLikesData = {
  body?: never;
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}/likes';
};

export type DeletePostsByIdLikesErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeletePostsByIdLikesResponses = {
  /**
   * Success - No Content
   */
  204: void;
};

export type DeletePostsByIdLikesResponse = DeletePostsByIdLikesResponses[keyof DeletePostsByIdLikesResponses];

export type PutPostsByIdLikesData = {
  body?: never;
  path: {
    /**
     * ULID
     *
     * Universally Unique Lexicographically Sortable Identifier (e.g. 01GEESHPQQ4NJKNZJN9AKWQW6G)
     */
    id: string;
  };
  query?: never;
  url: '/posts/{id}/likes';
};

export type PutPostsByIdLikesErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutPostsByIdLikesResponses = {
  /**
   * Success - No Content
   */
  204: void;
};

export type PutPostsByIdLikesResponse = PutPostsByIdLikesResponses[keyof PutPostsByIdLikesResponses];

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * The offset for pagination of further calls. Defaults to 0 if omitted.
     */
    offset?: number;
    /**
     * The limit of items to return. Minimum is 1, maximum is 1000.
     * Defaults to 100.
     */
    limit?: number;
  };
  url: '/users';
};

export type GetUsersErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetUsersResponses = {
  /**
   * Success
   */
  200: UserPaginatedResult;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PatchUsersData = {
  body?: UpdateUserData;
  path?: never;
  query?: never;
  url: '/users';
};

export type PatchUsersErrors = {
  /**
   * Bad Request - Some fields were set to empty string
   */
  400: unknown;
  /**
   * Not Found - The user was not found in the database
   */
  404: unknown;
  /**
   * Conflict - The username is already taken
   */
  409: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PatchUsersResponses = {
  /**
   * Success - The user profile was updated
   */
  204: void;
};

export type PatchUsersResponse = PatchUsersResponses[keyof PatchUsersResponses];

export type GetUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type GetUsersByIdErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetUsersByIdResponses = {
  /**
   * Success
   */
  200: User;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type DeleteUsersAvatarData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/avatar';
};

export type DeleteUsersAvatarErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteUsersAvatarResponses = {
  /**
   * Success - Avatar deleted
   */
  204: void;
};

export type DeleteUsersAvatarResponse = DeleteUsersAvatarResponses[keyof DeleteUsersAvatarResponses];

export type PutUsersAvatarData = {
  body?: {
    /**
     * Media file for the upload.
     */
    media?: Blob | File;
  };
  path?: never;
  query?: never;
  url: '/users/avatar';
};

export type PutUsersAvatarErrors = {
  /**
   * Bad Request - The uploaded file was too large, missing, or not an image
   */
  400: unknown;
  /**
   * Not Found - User with the given ID was not found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutUsersAvatarResponses = {
  /**
   * Success - New Avatar URL
   */
  200: unknown;
};

export type DeleteUsersByIdFollowersData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}/followers';
};

export type DeleteUsersByIdFollowersErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type DeleteUsersByIdFollowersResponses = {
  /**
   * Success - No Content
   */
  204: void;
};

export type DeleteUsersByIdFollowersResponse = DeleteUsersByIdFollowersResponses[keyof DeleteUsersByIdFollowersResponses];

export type GetUsersByIdFollowersData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    /**
     * The offset for pagination of further calls. Defaults to 0 if omitted.
     */
    offset?: number;
    /**
     * The limit of items to return. Minimum is 1, maximum is 1000.
     * Defaults to 100.
     */
    limit?: number;
  };
  url: '/users/{id}/followers';
};

export type GetUsersByIdFollowersErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetUsersByIdFollowersResponses = {
  /**
   * Success
   */
  200: UserPaginatedResult;
};

export type GetUsersByIdFollowersResponse = GetUsersByIdFollowersResponses[keyof GetUsersByIdFollowersResponses];

export type PutUsersByIdFollowersData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}/followers';
};

export type PutUsersByIdFollowersErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type PutUsersByIdFollowersResponses = {
  /**
   * Success - No Content
   */
  204: void;
};

export type PutUsersByIdFollowersResponse = PutUsersByIdFollowersResponses[keyof PutUsersByIdFollowersResponses];

export type GetUsersByIdFolloweesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    /**
     * The offset for pagination of further calls. Defaults to 0 if omitted.
     */
    offset?: number;
    /**
     * The limit of items to return. Minimum is 1, maximum is 1000.
     * Defaults to 100.
     */
    limit?: number;
  };
  url: '/users/{id}/followees';
};

export type GetUsersByIdFolloweesErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetUsersByIdFolloweesResponses = {
  /**
   * Success
   */
  200: UserPaginatedResult;
};

export type GetUsersByIdFolloweesResponse = GetUsersByIdFolloweesResponses[keyof GetUsersByIdFolloweesResponses];

export type GetPostsSseData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/posts/_sse';
};

export type GetPostsSseErrors = {
  /**
   * Internal Server Error
   */
  500: unknown;
};

export type GetPostsSseResponses = {
  /**
   * Event stream that contains new or updated posts.
   */
  200: Array<
    | {
        /**
         * ID of the event.
         */
        readonly id: unknown;
        /**
         * Event type.
         */
        event: 'postCreated';
        data: Post;
      }
    | {
        /**
         * ID of the event.
         */
        readonly id: unknown;
        /**
         * Event type.
         */
        event: 'postCreated';
        data: Reply;
      }
    | {
        /**
         * ID of the event.
         */
        readonly id: unknown;
        /**
         * Event type.
         */
        event: 'postUpdated';
        data: PostBase;
      }
    | {
        /**
         * ID of the event.
         */
        readonly id: unknown;
        /**
         * Event type.
         */
        event: 'postDeleted';
        data: DeletedPost;
      }
    | {
        /**
         * ID of the event.
         */
        readonly id: unknown;
        /**
         * Event type.
         */
        event: 'postLiked';
        data: LikeInfo;
      }
    | {
        /**
         * ID of the event.
         */
        readonly id: unknown;
        /**
         * Event type.
         */
        event: 'postUnliked';
        data: LikeInfo;
      }
  >;
};

export type GetPostsSseResponse = GetPostsSseResponses[keyof GetPostsSseResponses];
